### PR TITLE
About us page

### PR DESCRIPTION
**Pull request by nirmitparikh8**
Added the new team to the website.

### CODE REVIEW

**Comment by Dhvani35729** [comment]
Heet's, Saakshi's, and Kyle's image are not right

**Comment by Dhvani35729** [comment]
Also, you got everyone's bio and picture approved by them?

**Comment by Dhvani35729** [comment]
Make all the bio's consistent in description of grade.
Remove "twelfth grade" and make everything "grade 12 student", "grade 11 student", etc.

**Comment by Dhvani35729** [comment]
Saakshi's role is not correct...

**Comment by Dhvani35729** [comment]
Remove school from the bio's since not everybody has it

**Comment by Dhvani35729** [comment]
Aneri's bio is missing "student" after "university"

**Comment by Dhvani35729** [comment]
remove "Current Board of Directors".
Rename "MEET THE TEAM" to "MEET THE CURRENT TEAM"
Rename "PREVIOUS BOARD DIRECTORS", to "PREVIOUS TEAM MEMBERS"

**Comment by Dhvani35729** [comment]
Try putting the growth director in one row if it fits

**Comment by nirmitparikh8** [comment]
> Heet's, Saakshi's, and Kyle's image are not right

Wdym

**Comment by nirmitparikh8** [comment]
> See comments. Also, why is there a git showing a difference in our old images, like "param.jpg" should not have changed...

I made all images the same siz so that it would be consistent, and it also works fine.

**Comment by nirmitparikh8** [comment]
> Also, you got everyone's bio and picture approved by them?

Yes

**Comment by nirmitparikh8** [comment]
> Make all the bio's consistent in description of grade.
> Remove "twelfth grade" and make everything "grade 12 student", "grade 11 student", etc.

Ok

**Comment by nirmitparikh8** [comment]
> Saakshi's role is not correct...

Srry didn’t see that, I will change it.

**Comment by nirmitparikh8** [comment]
> Remove school from the bio's since not everybody has it

Sounds good

**Comment by nirmitparikh8** [comment]
> Aneri's bio is missing "student" after "university"

Ok I will fix that

**Comment by nirmitparikh8** [comment]
> remove "Current Board of Directors".
> Rename "MEET THE TEAM" to "MEET THE CURRENT TEAM"
> Rename "PREVIOUS BOARD DIRECTORS", to "PREVIOUS TEAM MEMBERS"

Will do

**Comment by nirmitparikh8** [comment]
> Try putting the growth director in one row if it fits

I will try

**Comment by Dhvani35729** [comment]
> > Heet's, Saakshi's, and Kyle's image are not right
> 
> I fixed Heet's but didn't see anything wrong with the other two images.

Heet's image is still not proper.

**Comment by KrishKrosh** [comment]
Saakshi, kyle, priyank, and saptarshis pictures look stretched weirdly. Did u crop them or stretch them?

**Comment by KrishKrosh** [comment]
> See comments. Also, why is there a git showing a difference in our old images, like "param.jpg" should not have changed...

I think nirmit may have compressed the images? Nirmit can you confirm this.

**Comment by nirmitparikh8** [comment]
I tried my best to keep every single image in proper resolution, I feel like Kyle's and Spatarshi's image is a bit weird. I asked them for a new one and used Saakshi's old image.

**Comment by nirmitparikh8** [comment]
> Saakshi, kyle, priyank, and saptarshis pictures look stretched weirdly. Did u crop them or stretch them?

I had cropped them but the image was a bit weird. For priyank I compressed it and squared it. It worked.

**Comment by nirmitparikh8** [comment]
@Dhvani35729 @KrishKrosh Do you think I should switch the images of Saptarshi's and Kyle's?

**Pull request merged**
