### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by Neel49**
This has all of the pictures in ignite and workshops in google photo galleries.

### CODE REVIEW

**Comment by Neel49** [comment]
Okay

**Comment by Neel49** [comment]
Okay

**Comment by Neel49** [comment]
Should I close the pull request

**Comment by Dhvani35729** [comment]
> Should I close the pull request

Nope. you need to pull master into this branch and then resolve conflicts.

**Comment by Neel49** [comment]
How do I pull master into this branch? And how do I compress tanisha.jpg, neel.jpg?

**Comment by Dhvani35729** [comment]
> How do I pull master into this branch? And how do I compress tanisha.jpg, neel.jpg?

@KrishKrosh will help you.

**Comment by Neel49** [comment]
Okay

**Comment by Neel49** [comment]
Okay can you look over the PR once more

**Comment by nirmitparikh8** [comment]
@Dhvani35729 I will fix the issues that @Neel49 cant fix. Just waiting for him to push the changes.

**Comment by nirmitparikh8** [comment]
> The following links on the Latest Works images are broken:
> 
> http://localhost:5000/fuse19
> http://localhost:5000/fuse17
> 
> The images in the Latest Works image should point to the corresponding event page. Some of them point to Brainsteam Alliance right now. Since we have a button on that event's page, should update those links.

I checked the fuse images on the latest works and the fuse links are fine. It's just that the images don't pop up. I will fix that

**Comment by nirmitparikh8** [comment]
> Images on home page for Latest Works section are not showing.

@Neel49 you removed the images that were being used. The images in latest works are missing in the public folder. Lets get on a call to fix this.

**Comment by nirmitparikh8** [comment]
All of the pages have been fixed.

**Pull request merged**
